### ISSUE TITLE
Support for MS teams through HELM and detailed logs in case of unsuccessful notification to MS TEAM incoming webhook

### ISSUE THREAD

**Issue by Lakshmisowmya** [bitnami/bitnami-docker-kubewatch#5]
Does this have support to MSTEAMS channel ?

**Comment by miguelaeh** [comment]
Hi @Lakshmisowmya ,
You can try to use the `WEBHOOK_URL` see the [configuration secction](https://github.com/bitnami/bitnami-docker-kubewatch#environment-variables) on the README.

**Comment by Lakshmisowmya** [comment]
Thanks @miguelaeh it is working with webhook.

I was using below conf as an example which did not work.
https://github.com/bitnami-labs/kubewatch/blob/master/examples/conf/kubewatch.conf.msteams.yaml
 
I see couple of issues after installing kubewatch.

1.  Events are getting notified only hourly once but not immediate. Is there any setting that i need to modify to get notified immediately in MS teams.
2. Kubewatch pod logs shows "Message sent to webhook successfully" but i don't see them in the channel. Seems few of the notifications are missing. 

Steps to reporduce: 

Install kubewatch through helm. webhook url will be incoming webhook url for any MS teams channel.

helm install --name kubewatch stable/kubewatch --set=slack.enabled='false',webhook.enabled='true',webhook.url='XXX'

**Comment by miguelaeh** [comment]
Hi @Lakshmisowmya ,
So, does it work with `WEBHOOK_URL` right?

**Comment by Lakshmisowmya** [comment]
It is partially working but not fully functional. As i mentioned cards are getting created only hourly once and that too for a couple of minutes and nothing is working till next hour.

**Comment by miguelaeh** [comment]
Hi @Lakshmisowmya ,
I guess that behavior could be due to the configuration of the `WEBHOOK` itself. I mean, in the case of Office365, they use push notifications and maybe you have it configured to push only once an hour?

**Comment by Lakshmisowmya** [comment]
@miguelaeh There is no such setting as of webhooks in MS Teams incoming connectors.

**Comment by Lakshmisowmya** [comment]
Also the POD does not show the 429 error message.

When i tried to post a message through CURL to my webhook i then got a 

Webhook message delivery failed with error: Microsoft Teams endpoint returned HTTP error 429 with ContextId tcid=XYZ,server=XYZ

It would be helpful if POD shows the logs.

**Comment by carrodher** [comment]
Hi, there are decoupled processes for [`bitnami/bitnami-docker-kubewatch`](https://github.com/bitnami/bitnami-docker-kubewatch) and [`bitnami-labs/kubewatch`](https://github.com/bitnami-labs/kubewatch).
Please, take a look at my comment here: https://github.com/bitnami/bitnami-docker-kubewatch/pull/4#issuecomment-511424450 for more information regarding this topic.
