### ISSUE TITLE
Slack message title as variable

### ISSUE THREAD

**Issue by 97turbotalon** [bitnami/bitnami-docker-kubewatch#7]
Can the slack title be changed to a variable that can be read from an env var or the kubewatch configmap?
Currently the slack message title is locked to be "kubewatch"

**Comment by rafariossaa** [comment]
Hi,
  I am sorry, currently that is not possible.
  Maybe you would like to open request to  the [kubewatch project](https://github.com/bitnami-labs/kubewatch).
